### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by AllTaken** [chrisfcarroll/MailMerge#4]
Merge fields appear to be case sensitive, when performing a merge using this library.
Merge fields are not usually case sensitive, when merging using Microsoft Word.

Would it be possible to change this behavior, or at least make it configurable?

**Comment by chrisfcarroll** [comment]
It would! You could do a pull request or I can get to it in a couple of days, later this week

**Comment by AllTaken** [comment]
I'll try to cook up a reasonable PR. Thank you.

**Comment by AllTaken** [comment]
PR #5 should fix this.

**Comment by chrisfcarroll** [comment]
Done in https://www.nuget.org/packages/MailMerge/2.4.0
