### ISSUE TITLE
"Broken" mergefield

### ISSUE THREAD

**Issue by AllTaken** [chrisfcarroll/MailMerge#7]
The following is from a Microsoft Word document with a mergefield with a fieldname of "SBEH":

```xml
	<w:r w:rsidR="007902E4">
		<w:fldChar w:fldCharType="begin"/>
	</w:r>
	<w:r w:rsidR="007902E4">
		<w:instrText xml:space="preserve"> MERGEFIELD  SBEH  \* M</w:instrText>
	</w:r>
	<w:r w:rsidR="007902E4">
		<w:instrText xml:space="preserve">ERGEFORMAT </w:instrText>
	</w:r>
	<w:r w:rsidR="007902E4">
		<w:fldChar w:fldCharType="separate"/>
	</w:r>
	<w:r>
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:t>«SBEH»</w:t>
	</w:r>
	<w:r w:rsidR="007902E4">
		<w:rPr>
			<w:noProof/>
		</w:rPr>
		<w:fldChar w:fldCharType="end"/>
	</w:r>
```

Unfortunately this does not get merged.

The following is logged:
`Noting <w:instrText 'SBEH '>...</w:instrText> for replacement with TL`
`Ignored sequence containing System.Xml.XmlElement because it was incomplete`

I'm guessing it has something to do with the node containing the "separate" node not being the immediate sibling of the mergefield node, because of the mergefield node being split into two.

I really don't know if this is OK, or if Microsoft are bending the rules, but I really need to merge this document 😅

**Comment by AllTaken** [comment]
Should be fixed by PR #8

**Comment by AllTaken** [comment]
Any chance of getting the PR reviewed and/or merged in the near future?

**Comment by killnine** [comment]
I have noticed this same issue. Very tricky to track down in the document. If this fix works can it be merged?

**Comment by chrisfcarroll** [comment]
Merged, will publish to nuget shortly

**Comment by chrisfcarroll** [comment]
https://www.nuget.org/packages/MailMerge/2.5.1
